if(EXISTS "/Users/josnyder/dev/MappingandProcessors/test/_tests_tests-b12d07c.cmake")
  include("/Users/josnyder/dev/MappingandProcessors/test/_tests_tests-b12d07c.cmake")
else()
  add_test(_tests_NOT_BUILT-b12d07c _tests_NOT_BUILT-b12d07c)
endif()
